swagger: '2.0'
info:
  title: Adani
  x-ibm-name: adani
  version: 1.0.0
  description: Remitter Validation with Intermediary Account API.
  termsOfService: 'http://TBD'
  contact:
    name: Adani Hazira Port Pvt Ltd.
    email: TBD@adani.com
    x-mis-contact-email:
      - Himanshu.Shekhar@adani.com
      - Shreeram.Moorthy@adani.com
    url: 'http://TBD'
  license:
    name: TBD
    url: 'http://TBD'
host: smartpay.adani.com
schemes:
  - https
basePath: /api
produces:
  - application/json
consumes:
  - application/json
securityDefinitions: {}
x-ibm-configuration:
  gateway: datapower-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
      - operation-switch:
          version: 1.0.0
          title: operation-switch
          case:
            - operations:
                - opValidate
              execute:
                - invoke:
                    version: 1.0.0
                    title: invoke
                    timeout: 60
                    verb: POST
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    target-url: 'https://target.com'
            - operations:
                - opReceipt
              execute:
                - invoke:
                    version: 1.0.0
                    title: invoke
                    timeout: 60
                    verb: POST
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    target-url: 'https://target.com'
          otherwise: []
  properties:
    target-url:
      value: 'http://example.com/operation-name'
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
definitions:
  validationRequest:
    properties:
      vid:
        type: string
        description: Unique actual Virtual Account No. of client.
        minLength: 0
        maxLength: 30
    type: object
    required:
      - vid
  validationResponse:
    properties:
      status:
        type: string
        description: Decision point for collection.
        enum:
          - Success
          - Failure
      message:
        type: object
        properties:
          success:
            type: boolean
            description: Status of the request.
          message:
            type: object
            properties:
              userName:
                type: string
                description: User Name.
                minLength: 0
                maxLength: 35
              validUser:
                type: string
                description: Is the user valid ?
                enum:
                  - 'yes'
                  - 'no'
              msg:
                type: string
                description: Mandatory if the status is FAIL.
                minLength: 0
                maxLength: 50
    type: object
    required:
      - status
  receiptRequest:
    properties:
      src:
        type: string
        description: Bank Name. Always "ICICI BANK LTD"
        minLength: 0
        maxLength: 20
        default: ICICI BANK LTD
      vid:
        type: string
        description: Virtual Account Number.
        minLength: 0
        maxLength: 30
      amount:
        type: string
        description: Transaction Amount
        minLength: 0
        maxLength: 14
        pattern: '[0-9]{1,11}\.[0-9]{2}}'
      paymentType:
        type: string
        description: >-
          Payment Mode. "N"  for NEFT,  "R" for RTGS, "I" for Fund Transfer and
          "O" for IMPS.
        default: 'N'
        enum:
          - 'N'
          - R
          - I
          - O
      txid:
        type: string
        description: Unique Transaction Reference number generated by remitting bank.
        minLength: 0
        maxLength: 30
      currencyType:
        type: string
        description: Currency.
        default: INR
        minLength: 0
        maxLength: 10
      txDateTimestamp:
        type: string
        description: Transaction timestamp.
        minLength: 0
        maxLength: 20
        pattern: '^(3[01]|[12][0-9]|0[1-9])-(1[0-2]|0[1-9])-[0-9]{4}$'
    required:
      - src
      - vid
      - amount
      - txid
      - currencyType
      - txDateTimestamp
  receiptResponse:
    properties:
      status:
        type: string
        description: Decision point for collection.
        enum:
          - Success
          - Failure
      message:
        type: object
        properties:
          success:
            type: boolean
            description: Status of the request.
          message:
            type: object
            properties:
              msg:
                type: string
                description: Mandatory if the status is FAIL.
                minLength: 0
                maxLength: 50
    type: object
    required:
      - status
paths:
  /users/validateUser:
    post:
      tags:
        - Validation
      summary: Validates a Payment Transaction.
      description: Validate a payment transaction.
      operationId: opValidate
      parameters:
        - description: Validation Request
          in: body
          name: body
          schema:
            $ref: '#/definitions/validationRequest'
      responses:
        '200':
          description: Validation Response.
          schema:
            $ref: '#/definitions/validationResponse'
      consumes:
        - application/json
      produces:
        - application/json
  /invoicepayment/addPaymentFromBank:
    post:
      tags:
        - Receipt
      summary: Accept Payment Transaction.
      description: Accepts a payment transaction.
      operationId: opReceipt
      parameters:
        - description: Receipt Request
          in: body
          name: body
          schema:
            $ref: '#/definitions/receiptRequest'
      responses:
        '200':
          description: Receipt Response.
          schema:
            $ref: '#/definitions/receiptResponse'
