---
swagger: "2.0"
info:
  title: "Adani Receipt"
  x-ibm-name: "adani-receipt"
  version: "1.0.0"
  description: "Remitter Validation with Intermediary Account API."
schemes:
- "https"
basePath: "/api"
produces:
- "application/json"
consumes:
- "application/json"
securityDefinitions: {}
x-ibm-configuration:
  gateway: "datapower-gateway"
  type: "rest"
  phase: "realized"
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: "1.0.0"
        title: "invoke"
        timeout: 60
        verb: "POST"
        cache-response: "protocol"
        cache-ttl: 900
        stop-on-error: []
        target-url: "https://target.com"
  properties:
    target-url:
      value: "http://example.com/operation-name"
      description: "The URL of the target service"
      encoded: false
definitions:
  receiptRequest:
    properties:
      src:
        type: "string"
        description: "Bank Name. Always \"ICICI BANK LTD\""
      vid:
        type: "string"
        description: "Virtual Account Number."
      amount:
        type: "string"
        description: "Transaction Amount"
      paymentType:
        type: "string"
        description: "Payment Mode. \"N\"  for NEFT,  \"R\" for RTGS, \"I\" for Fund\
          \ Transfer and \"O\" for IMPS."
      txid:
        type: "string"
        description: "Unique Transaction Reference number generated by remitting bank."
      currencyType:
        type: "string"
        description: "Currency."
        default: "INR"
      txDateTimestamp123:
        type: "string"
        description: "Transaction timestamp."
paths:
  /invoicepayment/addPaymentFromBank:
    post:
      tags:
      - "Receipt"
      summary: "Accept Payment Transaction."
      description: "Accepts a payment transaction."
      operationId: "opReceipt"
      parameters:
      - description: "Receipt Request"
        in: "body"
        name: "body"
        schema:
          $ref: "#/definitions/receiptRequest"
      responses:
        200:
          description: "Receipt Response."
