---
swagger: "2.0"
info:
  title: "Adani Validate"
  x-ibm-name: "adani-validate"
  version: "1.0.0"
  description: "Remitter Validation with Intermediary Account API."
host: "smartpay.adani.com"
schemes:
- "https"
basePath: "/api"
produces:
- "application/json"
consumes:
- "application/json"
securityDefinitions: {}
x-ibm-configuration:
  gateway: "datapower-gateway"
  type: "rest"
  phase: "realized"
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        version: "1.0.0"
        title: "invoke"
        timeout: 60
        verb: "POST"
        cache-response: "protocol"
        cache-ttl: 900
        stop-on-error: []
        target-url: "https://target.com"
  properties:
    target-url:
      value: "http://example.com/operation-name"
      description: "The URL of the target service"
      encoded: false
definitions:
  validationRequest:
    properties:
      vid:
        type: "string"
        description: "Unique actual Virtual Account No. of client."
    type: "object"
    required:
    - "vid"
  validationResponse:
    properties:
      status:
        type: "string"
        description: "Decision point for collection."
      message:
        type: "object"
        properties:
          success:
            type: "boolean"
            description: "Status of the request."
          message:
            type: "object"
            properties:
              userName:
                type: "string"
                description: "User Name."
              validUser:
                type: "string"
                description: "Is the user valid ?"
              msg:
                type: "string"
                description: "Mandatory if the status is FAIL."
    type: "object"
    required:
    - "status"
paths:
  /users/validateUser:
    post:
      tags:
      - "Validation"
      summary: "Validates a Payment Transaction."
      description: "Validate a payment transaction."
      operationId: "opValidate"
      parameters:
      - description: "Validation Request"
        in: "body"
        name: "body"
        schema:
          $ref: "#/definitions/validationRequest"
      responses:
        200:
          description: "Validation Response."
          schema:
            $ref: "#/definitions/validationResponse"
      consumes:
      - "application/json"
      produces:
      - "application/json"
