swagger: '2.0'
info:
  title: ECollection
  x-ibm-name: ecollection
  version: 1.0.0
host: $(catalog.host)
schemes:
  - https
basePath: /ecollection
produces:
  - application/json
consumes:
  - application/json
security:
  - clientId: []
    clientSecret: []
securityDefinitions:
  clientSecret:
    type: apiKey
    name: X-IBM-Client-Secret
    in: header
  clientId:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          target-url: 'https://api-dev.lendbox.in/v1/bank/transaction'
          verb: POST
          username: jayan.unni@in.ibm.com
          password: P@ssw0rd!
    catch: []
  phase: realized
  gateway: datapower-gateway
  type: rest
  application-authentication:
    certificate: false
tags: []
definitions:
  RspBody:
    description: ''
    type: object
    properties:
      Virtual Account Number Verification OUT:
        type: array
        items:
          properties:
            Client Code:
              type: string
            Virtual Account Number:
              type: string
            Transaction Amount:
              type: number
            UTR number:
              type: string
            Sender Name:
              type: string
            Date:
              type: string
            Sender IFSC_Code:
              type: string
            Remitter Account Number:
              type: string
            Mode:
              type: string
            Status:
              type: string
            Reject Reason:
              type: string
          type: object
    example: >-
      {"Virtual Account Number Verification OUT":[{"Client Code":"LEND","Virtual
      Account Number":"LEND0101910000000001","Transaction Amount":100000,"UTR
      number":"HDFC111115935","Sender Name":"Test Remitter
      1","Date":"10/04/2019","Sender IFSC_Code":"HDFC0000015","Remitter Account
      Number":"01431050032611","Mode":"N","Status":"ACCEPT","Reject
      Reason":""}]}
  ReqBody:
    description: ''
    type: object
    properties:
      Virtual Account Number Verification OUT:
        type: array
        items:
          properties:
            Client Code:
              type: string
            Virtual Account Number:
              type: string
            Transaction Amount:
              type: number
            UTR number:
              type: string
            Sender Name:
              type: string
            Date:
              type: string
            Sender IFSC_Code:
              type: string
            Remitter Account Number:
              type: string
            Mode:
              type: string
          type: object
    example: >-
      {"Virtual Account Number Verification OUT":[{"Client Code":"LEND","Virtual
      Account Number":"LEND0101910000000001","Transaction Amount":100000,"UTR
      number":"HDFC111115935","Sender Name":"Test Remitter
      1","Date":"10/04/2019","Sender IFSC_Code":"HDFC0000015","Remitter Account
      Number":"01431050032611","Mode":"N"}]}
paths:
  /transaction:
    post:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/RspBody'
      parameters:
        - name: REQUEST
          required: false
          in: body
          schema:
            $ref: '#/definitions/ReqBody'
        - name: username
          type: string
          required: false
          in: header
        - name: password
          type: string
          required: false
          in: header
        - name: secret
          type: string
          required: false
          in: header
